# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
mod_id=rclone22modlib
mod_name = RClone22's ModLib
mod_group=rclone22.modsrc22.rclone22modlib
mod_version=1.0.0
mod_author=RCloneBm22/R2234bmgofan22_clone/RClone22
mod_description=A standalone mod, mod lib and mod api, contains core mod and mixins.
mod_url=...
mod_credits=The authors are this mod creator
minecraft_version=1.12.2
forge_version=14.23.5.2860
mappings_channel=snapshot
mappings_version=20171003-1.12
mixins_forge_core_plugin_path=rclone22.modsrc22.rclone22modlib.mixins.MixinsLoadingPlugin

org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
